const net = require("net");
const rap = ["Is this the real life?",
  "Is this just fantasy?",
  "Caught in a landside,",
  "No escape from reality",
  "Open your eyes,",
  "Look up to the skies",
  "and see,",
  "I'm just a poor boy,",
  "I need no sympathy,",
  "Because I'm easy come",
  "easy go,",
  "Little high, little low,",
  "Any way the wind blows",
  "doesn't really matter to me",
  "to me",
  "Mamaaaaaaaa,",
  "Just killed a man,",
  "Put a gun ",
  "against his head",
  "pulled my trigger,",
  "Now he's dead",
  "Mamaaa",
  "life had just begun",
  "But now I've gone",
  "and thrown it all away",
  "Mama, oooh,",
  "Didn't mean to make you cry,",
  "If I'm not back again",
  "this time tomorrow",
  "Carry on, carry on",
  "as if nothing really matters",
  "Too late,",
  "my time has come,",
  "Sends shivers down my spine",
  "body's aching all",
  "The time",
  "Goodbye everybody",
  "I've got to go,",
  "Gotta leave you all behind",
  "and face the truuuth",
  "Mama, oooh",
  "I don't want to die,",
  "I sometimes wish I'd",
  "never been born at all.",
  "Guitar Solo",
  "I see a little",
  "silhouetto of a man,",
  "Scaramouch",
  "Scaramouch",
  "will you do the Fandango!",
  "Thunderbolts and lightning",
  "very, very frightening me",
  "Galileo, Galileo",
  "Galileo, Galileo",
  "Galileo, Figaro",
  "magnificoo OOO oo",
  "I'm just a poor boy ",
  "nobody loves me",
  "He's just a poor boy",
  "from a poor family,",
  "Spare him his life ",
  "from this monstrosity",
  "Easy come, easy go, ",
  "will you let me go",
  "Bismillah! No, ",
  "we will not let you go",
  "(Let him go!) ",
  "Bismillah!",
  "We will not let you go",
  "(Let him go!) ",
  "Bismillah! ",
  "We will not let you go",
  "(Let me go) ",
  "Will not let you go",
  "(Let me go)(Never) ",
  "Never let you go",
  "(Let me go) ",
  "(Never) let you go ",
  "(Let me go) Ah",
  "No, no, no, ",
  "no, no, no, no",
  "Oh mama mia",
  "mama mia",
  "mama mia, let me go",
  "Beelzebub,",
  "has a devil put aside ",
  "for me, ",
  "for me,",
  "For meeeeee!!!",
  "So you think you can stop ",
  "me and spit in my eye",
  "*Guitar Noises*",
  "So you think you can love me ",
  "and leave me to die",
  "Oh, baby, ",
  "can't do this to me, baby,",
  "Just gotta get out, ",
  "just gotta get right outta here",
  "Nothing really matters, ",
  "Anyone can see,",
  "Nothing really matters,",
  "Nothing really matters" ,
  "to meeeeeee",
  "Any way the wind blows...",
  "le fin"];

const roll = ["We're no strangers to love",
  "You know the rules and so do I",
  "A full commitment's what I'm thinking of",
  "You wouldn't get this from any other guy",
  "I just wanna tell you how I'm feeling",
  "Gotta make you understand",
  "Never gonna give you up",
  "Never gonna let you down",
  "Never gonna run around and desert you",
  "Never gonna make you cry",
  "Never gonna say goodbye",
  "Never gonna tell a lie and hurt you",
  "We've known each other for so long",
  "Your heart's been aching but you're too shy to say it",
  "Inside we both know what's been going on",
  "We know the game and we're gonna play it",
  "And if you ask me how I'm feeling",
  "Don't tell me you're too blind to see",
  "Never gonna give you up",
  "Never gonna let you down",
  "Never gonna run around and desert you",
  "Never gonna make you cry",
  "Never gonna say goodbye",
  "Never gonna tell a lie and hurt you",
  "Never gonna give you up",
  "Never gonna let you down",
  "Never gonna run around and desert you",
  "Never gonna make you cry",
  "Never gonna say goodbye",
  "Never gonna tell a lie and hurt you",
  "Never gonna give, never gonna give",
  "(Give you up)",
  "We've known each other for so long",
  "Your heart's been aching but you're too shy to say it",
  "Inside we both know what's been going on",
  "We know the game and we're gonna play it",
  "I just wanna tell you how I'm feeling",
  "Gotta make you understand",
  "Never gonna give you up",
  "Never gonna let you down",
  "Never gonna run around and desert you",
  "Never gonna make you cry",
  "Never gonna say goodbye",
  "Never gonna tell a lie and hurt you",
  "Never gonna give you up",
  "Never gonna let you down",
  "Never gonna run around and desert you",
  "Never gonna make you cry",
  "Never gonna say goodbye",
  "Never gonna tell a lie and hurt you",
  "Never gonna give you up",
  "Never gonna let you down",
  "Never gonna run around and desert you",
  "Never gonna make you cry",
  "Never gonna say goodbye"];

  
const {IP, PORT} = require('./constants');
const connect = function() {
  // create server
  const conn = net.createConnection({
    host: IP,
    port: PORT
  });
  conn.setEncoding("utf8");

  // On connect
  conn.on("connect", () => {
    console.log('Connected!!!');
    conn.write("Name: JDT");
    let timer = 5000;
    for (let item of roll) {
      setTimeout(() => {
        conn.write(`Say: ${item}`);
      }, timer);
      
      timer += 1500;
    }
  });

  // recieve data from server
  conn.on("data", (data) => {
    console.log(data);
  });

  return conn;
};

module.exports = connect;